import { AETProject } from '../types';

export const createMockProject = (): AETProject => ({
  id: 'mock-1',
  reportType: 'AET',
  companyName: 'Metalúrgica São Paulo Ltda',
  fantasyName: 'MetalSP',
  cnpj: '12.345.678/0001-90',
  address: 'Rua das Indústrias, 1500 - Distrito Industrial, Guarulhos - SP, CEP 07220-000',
  unit: 'Unidade Guarulhos',
  product: 'Peças automotivas estampadas',
  riskDegree: '3',
  location: 'Guarulhos - SP',
  consultoriaLogoDataUrl: '',
  companyLogoDataUrl: '',
  responsibleLogoDataUrl: '',
  evaluatorName: 'Dr. Carlos Eduardo Mendes',
  evaluatorFormation: 'Fisioterapeuta',
  evaluatorCrefito: 'CREFITO-3/12345-F',
  evaluatorCompany: 'ErgoConsult Ltda',
  evaluatorSignatureDataUrl: '',
  date: '2024-03-15',
  introErgonomia: '',
  introObjetivo: '',
  introMetodologia: '',
  functions: [
    {
      id: 'func-1',
      name: 'Operador de Prensa',
      unit: 'Unidade Guarulhos',
      sector: 'Estamparia',
      analysisDate: '2024-03-15',
      numEmployees: '12',
      demandOrigin: 'Demanda originada pela necessidade de atendimento à NR-17 e queixas de desconforto relatadas pelos colaboradores do setor de estamparia.',
      objective: 'Avaliar as condições ergonômicas do posto de trabalho do operador de prensa, identificando fatores de risco e propondo melhorias.',
      demandFound: 'Posto passível de investigações ergonômicas',
      marketSituation: 'Empresa fornecedora tier-2 para montadoras, com demanda crescente de 15% ao ano.',
      product: 'Peças estampadas em aço carbono para sistemas de suspensão automotiva.',
      productionLocation: 'Galpão principal - Linha de estamparia 1',
      productionDimension: 'Produção média de 8.000 peças/dia em 3 prensas hidráulicas de 150 ton.',
      productionGoals: 'Sim',
      qualityAnalysis: 'Inspeção visual 100% + controle dimensional amostral a cada 500 peças com paquímetro e gabarito.',
      qualityEvaluator: 'Líder de Célula',
      shifts: '3 turnos',
      shiftStart: '06:00',
      shiftEnd: '14:20',
      workDays: 'Segunda a Sábado',
      overtime: 'Eventualmente',
      pauses: 'Intervalo de 1 hora para refeição + 2 pausas de 10 minutos (manhã e tarde).',
      taskRotation: 'Sim',
      bathroomDistance: 'Menos de 50 m',
      bathroomCondition: 'Adequada',
      hierarchyOrganogram: 'Gerente Industrial → Supervisor de Produção → Líder de Célula → Operador de Prensa',
      workspaceDescription: 'Galpão industrial com pé-direito de 8m, piso em concreto polido, iluminação mista (natural via telhas translúcidas + artificial). Área por operador: aprox. 12m².',
      collabFormation: 'Ensino médio completo + treinamento interno de 40h em operação de prensa.',
      collabTurn: '1º turno (06:00 às 14:20)',
      opinionGender: 'Masculino',
      opinionAge: '28 a 45 anos',
      opinionTime: '5 anos',
      opinionObjective: 'Operar a prensa de forma segura e eficiente, garantindo qualidade das peças.',
      opinionThermal: 'Quente',
      opinionVentilation: 'Insuficiente',
      opinionVentilationDesc: 'Ventilação natural insuficiente. Ventiladores industriais presentes mas com distribuição irregular.',
      opinionLightingSens: 'Adequada',
      opinionLightingDesc: 'Iluminação considerada boa na maioria dos postos, com pontos de sombra próximos às colunas.',
      opinionAcoustics: 'Muito ruidoso',
      opinionEPI: 'Protetor auricular tipo plug, óculos de proteção, luva de raspa, bota com biqueira de aço, avental de raspa.',
      opinionEquip: 'Parcialmente adequados',
      opinionCycle: 'Ciclo adequado, porém repetitivo. Trabalhador sugere maior variação nas tarefas.',
      opinionLayout: 'Layout funcional, mas espaço entre prensas poderia ser maior para movimentação de materiais.',
      opinionDifficulties: 'Peso das chapas na alimentação manual, postura curvada para pegar peças da caixa de material.',
      opinionPressure: 'Pressão moderada',
      opinionRelationship: 'Bom',
      opinionLeadership: 'Aberta',
      opinionMaintenanceInfluence: 'Interfere raramente',
      opinionMaintenanceDelay: 'Atrasos eventuais na manutenção da prensa 02 geram parada de linha.',
      opinionIntercurrences: 'Quebra de ferramenta (1-2x/mês), falta de material ocasional, problemas na ponte rolante.',
      effortDynamic: 'Movimentos repetitivos de membros superiores na alimentação da prensa (aprox. 8-12 ciclos/min). Flexão/extensão de cotovelo e punho predominantes.',
      effortStatic: 'Manutenção de postura em pé durante todo o turno. Sustentação de chapas metálicas (2-5 kg) durante posicionamento no molde.',
      timeAnalysis: 'Ciclo operacional: 5-7 segundos por peça. Tempo efetivo de operação: 85% do turno. Micropausa natural entre ciclos: 2-3 segundos.',
      loadCarrying: 'Caixas de peças acabadas: 8-15 kg. Chapas individuais: 2-5 kg. Transporte manual em distância de até 3 metros.',
      displacement: 'Inferior a 2 km/dia (deslocamento médio de 200m/hora entre prensa, bancada de inspeção e área de embalagem).',
      maintenanceDesc: 'Manutenção preventiva programada mensalmente. Operador realiza limpeza diária e lubrificação básica da prensa.',
      maintenanceCausesDelay: 'Raramente',
      logisticsInfluence: 'Sim',
      logisticsDelay: 'Atrasos na logística interna ocorrem 2-3x por semana, gerando acúmulo de trabalho posterior.',
      reworkDesc: 'Retrabalho por defeitos dimensionais (rebarbas, amassados). Refugo médio de 2%.',
      reworkWeek: '3-5 peças/dia',
      reworkNotApplicable: false,
      usesEquipment: true,
      usesEPI: true,
      equipmentList: [
        { id: 'eq-1', name: 'Prensa Hidráulica 150 ton', quantity: '3', dimensions: '2500x1800x3000 mm', principle: 'hidraulico', condition: 'Regular', observations: 'Prensa 02 com vibração acima do normal.' },
        { id: 'eq-2', name: 'Mesa de Alimentação', quantity: '3', dimensions: '1200x800x850 mm', principle: 'manual', condition: 'Regular', observations: 'Altura fixa, não regulável.' },
        { id: 'eq-3', name: 'Bancada de Inspeção', quantity: '2', dimensions: '1500x700x900 mm', principle: 'manual', condition: 'Boa', observations: '' },
      ],
      epiList: [
        { id: 'epi-1', name: 'Protetor auricular tipo plug', mandatory: true, occasional: false, location: 'Todo o setor de estamparia', observations: 'CA vigente' },
        { id: 'epi-2', name: 'Óculos de proteção', mandatory: true, occasional: false, location: 'Operação de prensa', observations: '' },
        { id: 'epi-3', name: 'Luva de raspa', mandatory: true, occasional: false, location: 'Manuseio de chapas', observations: '' },
        { id: 'epi-4', name: 'Bota com biqueira de aço', mandatory: true, occasional: false, location: 'Todo o setor', observations: '' },
      ],
      equipProblems: 'Prensa 02: vibração acima do normal no curso de descida. Mesa de alimentação com altura fixa não regulável.',
      cyclePrescribed: 'VIDE PGR',
      cycleReal: '1. Pegar chapa da caixa (frequente flexão de tronco)\n2. Ajustar posição da chapa manualmente no molde\n3. Verificar posicionamento visual\n4. Acionar bimanual\n5. Aguardar ciclo (aproveita para ajustar EPIs)\n6. Retirar peça com ambas as mãos\n7. Inspeção rápida visual + tátil\n8. Depositar na caixa ou separar para retrabalho\n9. Eventualmente limpar rebarbas do molde',
      postureSittingPct: 5,
      postureStandingPct: 85,
      postureWalkingPct: 5,
      postureCrouchingPct: 5,
      postureOtherPct: 0,
      postureOtherDescription: '',
      meioAmbiente: 'Vide LTCAT / Vide PGR',
      illumination: {
        location: 'Setor de Estamparia - Linha 1',
        date: '2024-03-15',
        lightingType: 'Mista',
        introduction: 'A medição de iluminância foi realizada conforme os procedimentos técnicos da NHO 11 da Fundacentro.',
        objective: 'Verificar se os níveis de iluminamento no posto de trabalho do operador de prensa atendem aos requisitos da NBR 8995-1.',
        justification: 'Atendimento à NR-17, item 17.5.3, que estabelece condições adequadas de iluminação nos ambientes de trabalho.',
        environmentDescription: 'Galpão industrial com telhas metálicas, pé-direito de 8m, paredes em alvenaria pintadas de branco.',
        lightingSystem: 'Luminárias LED industrial 200W, distribuídas em 2 linhas sobre a área de trabalho, altura de instalação 6m.',
        activities: 'Operação de prensa com necessidade de inspeção visual de peças.',
        criteria: 'NBR 8995-1 - Iluminação de ambientes internos. Nível recomendado para trabalho em prensa: 300 lux (mínimo).',
        measuredValues: 'Ponto 1 (mesa): 420 lux | Ponto 2 (molde): 380 lux | Ponto 3 (inspeção): 350 lux | Ponto 4 (caixa material): 180 lux',
        referenceValue: '300 lux (NBR ISO/CIE 8995-1)',
        formula: 'Emed = Σ(Ei) / n',
        resultLux: '332 lux (média)',
        interpretation: 'A iluminância média atende ao mínimo de 300 lux. Porém, o ponto 4 (caixa de material) está abaixo do recomendado, necessitando iluminação suplementar.',
        normativeReference: 'NHO 11 – Fundacentro; ABNT NBR ISO/CIE 8995-1:2013',
        conclusion: 'inadequada',
        conclusionText: 'A iluminação do setor é parcialmente inadequada. O ponto 4 requer intervenção imediata com luminária suplementar.',
        checklist: [
          { id: 'c1', description: 'As luminárias estão limpas e em bom estado?', compliant: 'sim', recommendedAction: '', deadline: '', responsible: '', observations: '' },
          { id: 'c2', description: 'Existem lâmpadas queimadas?', compliant: 'nao', recommendedAction: '', deadline: '', responsible: '', observations: 'Todas funcionando' },
          { id: 'c3', description: 'Há ofuscamento direto ou refletido?', compliant: 'nao', recommendedAction: '', deadline: '', responsible: '', observations: '' },
          { id: 'c4', description: 'A iluminação é uniforme na área de trabalho?', compliant: 'nao', recommendedAction: 'Instalar luminária adicional sobre área de material', deadline: '2024-05-15', responsible: 'Manutenção', observations: 'Ponto 4 abaixo do recomendado' },
        ],
      },
      scientificMethods: [
        { id: 'sm-1', methodName: 'RULA', description: 'O método RULA (Rapid Upper Limb Assessment) avalia a exposição dos trabalhadores a fatores de risco para membros superiores.', result: '5', riskClassification: 'Amarelo – Risco Moderado', interpretation: 'Investigar e implantar mudanças. Risco moderado para membros superiores com possibilidade de desconforto musculoesquelético a médio prazo.', imageDataUrl: '', recommendations: 'Adequar altura da mesa de alimentação. Reduzir flexão de punho na alimentação.' },
        { id: 'sm-2', methodName: 'REBA', description: 'O método REBA (Rapid Entire Body Assessment) avalia posturas de corpo inteiro em tarefas dinâmicas.', result: '7', riskClassification: 'Laranja – Risco Substancial', interpretation: 'Necessária investigação e implementação de mudanças em curto prazo.', imageDataUrl: '', recommendations: 'Elevar as caixas de material para reduzir flexão de tronco.' },
      ],
      images: [],
      diagnosis: 'A análise ergonômica da função de Operador de Prensa evidenciou aspectos positivos como o rodízio entre máquinas, a abertura da liderança a sugestões e o bom relacionamento interpessoal.\n\nForam identificados riscos moderados relacionados à postura predominantemente em pé (85%), com episódios frequentes de flexão de tronco para alimentação da prensa, movimentos repetitivos de membros superiores (8-12 ciclos/min) e manuseio de chapas (2-5 kg) com postura desfavorável.\n\nOs métodos RULA (score 5 – Moderado) e REBA (score 7 – Substancial) confirmam a necessidade de intervenção ergonômica.\n\nRecomenda-se atenção prioritária à adequação da altura de alimentação e à reorganização das caixas de material, conforme detalhado no inventário de riscos.',
      riskLevel: 'Moderado',
      improvements: [
        { id: 'imp-1', photoDataUrl: '', hazard: 'Flexão de tronco acentuada para pegar chapas da caixa de material posicionada no nível do piso.', probability: '3 – Provável', severity: '2 – Moderada', grossRiskLevel: '6', riskClassification: 'Moderado', riskEvaluation: 'P3 x S2 = 6', actions: 'Elevar a caixa de material com suporte regulável em altura (800-1000mm do piso). Utilizar mesa pantográfica para manter nível constante.', attenuationProbability: 'Alta', deadline: '2024-06-15', responsible: 'Engenharia de Processos', observations: 'Investimento estimado: R$ 3.500,00 por posto.' },
        { id: 'imp-2', photoDataUrl: '', hazard: 'Mesa de alimentação com altura fixa, inadequada para operadores de diferentes estaturas.', probability: '3 – Provável', severity: '2 – Moderada', grossRiskLevel: '6', riskClassification: 'Moderado', riskEvaluation: 'P3 x S2 = 6', actions: 'Instalar sistema de regulagem de altura na mesa de alimentação ou fornecer estrados reguláveis.', attenuationProbability: 'Média', deadline: '2024-07-15', responsible: 'Manutenção', observations: '' },
        { id: 'imp-3', photoDataUrl: '', hazard: 'Iluminação insuficiente (180 lux) na área de armazenamento de material, abaixo do mínimo de 300 lux.', probability: '4 – Frequente', severity: '1 – Leve', grossRiskLevel: '4', riskClassification: 'Baixo / Tolerável', riskEvaluation: 'P4 x S1 = 4', actions: 'Instalar luminária LED adicional de 100W direcionada à área de material.', attenuationProbability: 'Alta', deadline: '2024-04-15', responsible: 'Manutenção Elétrica', observations: 'Custo estimado: R$ 450,00.' },
      ],
      checklistAnswers: [],
      rulaScore: 'Amarelo – Investigar',
    },
    {
      id: 'func-2',
      name: 'Auxiliar de Produção',
      unit: 'Unidade Guarulhos',
      sector: 'Embalagem',
      analysisDate: '2024-03-16',
      numEmployees: '8',
      demandOrigin: 'Complemento da AET do setor produtivo, incluindo a etapa de embalagem e expedição.',
      objective: 'Avaliar as condições ergonômicas do auxiliar de produção no setor de embalagem.',
      demandFound: 'Posto passível de modificações ergonômicas',
      marketSituation: 'Demanda estável com picos sazonais.',
      product: 'Embalagem de peças estampadas para expedição.',
      productionLocation: 'Galpão de embalagem - Setor de expedição',
      productionDimension: 'Embalagem de aprox. 2.000 peças/dia distribuídas em caixas de 20 unidades.',
      productionGoals: 'Informais',
      qualityAnalysis: 'Conferência de quantidade e inspeção visual antes do fechamento da caixa.',
      qualityEvaluator: 'Supervisor de Expedição',
      shifts: '2 turnos',
      shiftStart: '06:00',
      shiftEnd: '14:20',
      workDays: 'Segunda a Sábado',
      overtime: 'Eventualmente',
      pauses: 'Intervalo de 1 hora para refeição + 1 pausa de 15 minutos.',
      taskRotation: 'Sim',
      bathroomDistance: 'Menos de 50 m',
      bathroomCondition: 'Adequada',
      hierarchyOrganogram: 'Gerente Industrial → Supervisor de Expedição → Auxiliar de Produção',
      workspaceDescription: 'Área coberta com bancadas de embalagem, esteiras transportadoras e área de paletização.',
      collabFormation: 'Ensino médio completo.',
      collabTurn: '1º turno',
      opinionGender: 'Misto',
      opinionAge: '22 a 40 anos',
      opinionTime: '3 anos',
      opinionObjective: 'Embalar peças de forma organizada e eficiente.',
      opinionThermal: 'Confortável',
      opinionVentilation: 'Adequada',
      opinionVentilationDesc: 'Boa ventilação natural e artificial.',
      opinionLightingSens: 'Adequada',
      opinionLightingDesc: 'Iluminação adequada em toda a área.',
      opinionAcoustics: 'Adequada',
      opinionEPI: 'Luvas de proteção, óculos, bota de segurança.',
      opinionEquip: 'Adequados',
      opinionCycle: 'Ciclo variado e não repetitivo.',
      opinionLayout: 'Layout adequado com boa circulação.',
      opinionDifficulties: 'Peso das caixas prontas (até 15kg).',
      opinionPressure: 'Sem pressão',
      opinionRelationship: 'Bom',
      opinionLeadership: 'Aberta',
      opinionMaintenanceInfluence: 'Não interfere',
      opinionMaintenanceDelay: 'Sem atrasos significativos.',
      opinionIntercurrences: 'Raras.',
      effortDynamic: 'Movimentos de pegar, posicionar e embalar peças. Esforço moderado com membros superiores.',
      effortStatic: 'Postura em pé com apoio eventual na bancada.',
      timeAnalysis: 'Ciclo de embalagem: 15-20 seg por caixa. Atividade dinâmica com variações conforme demanda.',
      loadCarrying: 'Caixas de 10-15 kg transportadas manualmente até o palete (2-3m). Frequência: 20-30 caixas/hora.',
      displacement: 'Entre 2 e 4 km/dia (deslocamento entre bancada, esteira e área de paletização).',
      maintenanceDesc: 'Manutenção simples de bancada e esteira realizada pela equipe de manutenção.',
      maintenanceCausesDelay: 'Não',
      logisticsInfluence: 'Sim',
      logisticsDelay: 'Influência moderada na sequência de trabalho; eventuais atrasos.',
      reworkDesc: 'Reembalagem por erro de quantidade. Baixo índice.',
      reworkWeek: '2-3 caixas/semana',
      reworkNotApplicable: false,
      usesEquipment: true,
      usesEPI: true,
      equipmentList: [
        { id: 'eq-4', name: 'Bancada de Embalagem', quantity: '4', dimensions: '1500x700x900 mm', principle: 'manual', condition: 'Boa', observations: '' },
        { id: 'eq-5', name: 'Seladora Térmica', quantity: '2', dimensions: '600x400x200 mm', principle: 'eletrico', condition: 'Boa', observations: '' },
        { id: 'eq-6', name: 'Paleteira Manual Hidráulica', quantity: '2', dimensions: '1500x680 mm', principle: 'hidraulico', condition: 'Regular', observations: 'Rodas desgastadas, dificultando movimentação.' },
      ],
      epiList: [
        { id: 'epi-5', name: 'Luvas de proteção', mandatory: true, occasional: false, location: 'Manuseio de peças', observations: '' },
        { id: 'epi-6', name: 'Óculos de proteção', mandatory: true, occasional: false, location: 'Setor de embalagem', observations: '' },
        { id: 'epi-7', name: 'Bota de segurança', mandatory: true, occasional: false, location: 'Todo o setor', observations: '' },
      ],
      equipProblems: 'Paleteira com rodas desgastadas, dificultando movimentação.',
      cyclePrescribed: 'VIDE PGR',
      cycleReal: '1. Pegar peças da esteira\n2. Conferir visualmente\n3. Posicionar na caixa com proteção\n4. Fechar e selar\n5. Colar etiqueta\n6. Carregar até palete (manual)\n7. Empilhar (até 3 níveis)',
      postureSittingPct: 5,
      postureStandingPct: 60,
      postureWalkingPct: 30,
      postureCrouchingPct: 5,
      postureOtherPct: 0,
      postureOtherDescription: '',
      meioAmbiente: 'Vide LTCAT / Vide PGR',
      illumination: {
        location: 'Setor de Embalagem',
        date: '2024-03-16',
        lightingType: 'Mista',
        introduction: 'Medição realizada conforme NHO 11 – Fundacentro.',
        objective: 'Verificar conformidade da iluminação no setor de embalagem.',
        justification: 'Atendimento à NR-17.',
        environmentDescription: 'Área coberta com telhas translúcidas e iluminação LED.',
        lightingSystem: 'Luminárias LED 150W em 3 linhas.',
        activities: 'Embalagem, inspeção visual e etiquetagem.',
        criteria: 'NBR 8995-1, nível recomendado: 300 lux.',
        measuredValues: 'Ponto 1: 450 lux | Ponto 2: 380 lux | Ponto 3: 410 lux',
        referenceValue: '300 lux (NBR ISO/CIE 8995-1)',
        formula: 'Emed = Σ(Ei) / n',
        resultLux: '413 lux (média)',
        interpretation: 'Todos os pontos acima do mínimo recomendado de 300 lux. Iluminação adequada.',
        normativeReference: 'NHO 11 – Fundacentro; ABNT NBR ISO/CIE 8995-1:2013',
        conclusion: 'adequada',
        conclusionText: 'A iluminação do setor de embalagem está adequada para as tarefas realizadas.',
        checklist: [
          { id: 'c5', description: 'Luminárias em bom estado?', compliant: 'sim', recommendedAction: '', deadline: '', responsible: '', observations: '' },
          { id: 'c6', description: 'Iluminação uniforme em toda a área?', compliant: 'sim', recommendedAction: '', deadline: '', responsible: '', observations: '' },
        ],
      },
      scientificMethods: [
        { id: 'sm-3', methodName: 'NIOSH', description: 'Equação de NIOSH para avaliação de levantamento manual de cargas.', result: 'IL = 1,8', riskClassification: 'Laranja – Risco Substancial', interpretation: 'Índice de Levantamento acima de 1,0, indicando risco relevante de lombalgia. Intervenção necessária.', imageDataUrl: '', recommendations: 'Reduzir peso das caixas para máx. 10kg ou utilizar auxílio mecânico para paletização.' },
      ],
      images: [],
      diagnosis: 'A análise ergonômica do Auxiliar de Produção evidenciou aspectos positivos como rodízio de tarefas, bom relacionamento com a liderança e ambiente com iluminação adequada.\n\nO risco principal identificado é o carregamento manual de caixas de 10-15 kg com flexão de tronco durante a paletização, com Índice de Levantamento NIOSH de 1,8 — acima do limite seguro de 1,0.\n\nRecomenda-se a redução do peso por caixa e a implantação de auxílios mecânicos (mesa elevatória) para a operação de paletização.',
      riskLevel: 'Substancial',
      improvements: [
        { id: 'imp-4', photoDataUrl: '', hazard: 'Carregamento manual de caixas de 10-15 kg com flexão de tronco durante paletização.', probability: '4 – Frequente', severity: '2 – Moderada', grossRiskLevel: '8', riskClassification: 'Moderado', riskEvaluation: 'P4 x S2 = 8', actions: 'Reduzir peso máximo por caixa para 10 kg. Implementar mesa elevatória para paletização.', attenuationProbability: 'Alta', deadline: '2024-05-30', responsible: 'Eng. Segurança', observations: '' },
        { id: 'imp-5', photoDataUrl: '', hazard: 'Paleteira manual com rodas desgastadas gerando força excessiva de empurrar/puxar.', probability: '3 – Provável', severity: '1 – Leve', grossRiskLevel: '3', riskClassification: 'Baixo / Tolerável', riskEvaluation: 'P3 x S1 = 3', actions: 'Substituir rodas da paleteira. Avaliar paleteira elétrica.', attenuationProbability: 'Alta', deadline: '2024-04-30', responsible: 'Manutenção', observations: '' },
      ],
      checklistAnswers: [],
      rulaScore: 'Verde – Aceitável',
    },
  ],
});
