import {
  AETProject,
  Company, Unit, Sector, StandardJobRole,
  EMPTY_FUNCTION,
  EMPTY_ILLUMINATION,
  DEFAULT_AEP_INTRO_ERGONOMIA,
  DEFAULT_AEP_INTRO_OBJETIVO,
  DEFAULT_AEP_INTRO_METODOLOGIA,
  DEFAULT_AET_INTRO_ERGONOMIA,
  DEFAULT_AET_INTRO_OBJETIVO,
  DEFAULT_AET_INTRO_METODOLOGIA,
  createEmptyAEPFunctionAssessment,
} from '../types';
import {
  MOCK_COMPANIES, MOCK_UNITS, MOCK_SECTORS, MOCK_JOB_ROLES,
} from './mockParameterData';

// ── Catalog helpers ──────────────────────────────────────────────────────────

export const getMockCompanyById = (id: string): Company => {
  const c = MOCK_COMPANIES.find(x => x.id === id);
  if (!c) throw new Error(`Mock company not found: ${id}`);
  return c;
};

export const getMockUnitById = (id: string): Unit => {
  const u = MOCK_UNITS.find(x => x.id === id);
  if (!u) throw new Error(`Mock unit not found: ${id}`);
  return u;
};

export const getMockSectorById = (id: string): Sector => {
  const s = MOCK_SECTORS.find(x => x.id === id);
  if (!s) throw new Error(`Mock sector not found: ${id}`);
  return s;
};

export const getMockJobRoleById = (id: string): StandardJobRole => {
  const r = MOCK_JOB_ROLES.find(x => x.id === id);
  if (!r) throw new Error(`Mock job role not found: ${id}`);
  return r;
};

export const buildAddressFromCompany = (company: Company): string =>
  `${company.logradouro}, ${company.numero} – ${company.bairro} – ${company.municipio}/${company.uf}`;

export const buildLocationFromCompany = (company: Company): string =>
  `${company.municipio} – ${company.uf}`;

// ── Project builders ─────────────────────────────────────────────────────────

export const buildMockAEPProjectFromCatalog = (): AETProject => {
  const company  = getMockCompanyById('company-padaria-horizonte');
  const unit     = getMockUnitById('unit-padaria-matriz');
  const sectAtt  = getMockSectorById('sector-padaria-atendimento');
  const sectProd = getMockSectorById('sector-padaria-producao');
  const roleAtt  = getMockJobRoleById('role-padaria-atendente-balcao');
  const roleProd = getMockJobRoleById('role-padaria-auxiliar-producao');

  return {
    id: 'mock-aep-1',
    reportType: 'AEP',
    companyName:  company.razaoSocial,
    fantasyName:  company.nomeFantasia,
    cnpj:         company.cnpj,
    address:      buildAddressFromCompany(company),
    unit:         unit.name,
    product:      company.product,
    riskDegree:   company.riskDegree,
    location:     buildLocationFromCompany(company),
    consultoriaLogoDataUrl:    '',
    companyLogoDataUrl:        '',
    responsibleLogoDataUrl:    '',
    evaluatorSignatureDataUrl: '',
    evaluatorName:       'Mariana Costa Albuquerque',
    evaluatorFormation:  'Fisioterapeuta do Trabalho e Ergonomista',
    evaluatorCrefito:    'CREFITO-1 123456-F',
    evaluatorCompany:    'ErgoPlus Consultoria em Saúde Ocupacional',
    date: '2026-01-15',
    introErgonomia:   DEFAULT_AEP_INTRO_ERGONOMIA,
    introObjetivo:    DEFAULT_AEP_INTRO_OBJETIVO,
    introMetodologia: DEFAULT_AEP_INTRO_METODOLOGIA,
    functions: [
      // ── Função 1: Atendente de Balcão ──────────────────────────────────────
      {
        ...EMPTY_FUNCTION,
        id:           'aep-f1',
        name:         roleAtt.name,
        unit:         unit.name,
        sector:       sectAtt.name,
        analysisDate: '2026-01-15',
        numEmployees: '4',
        ghe: 'GHE-01 Atendimento e Balcão',
        demandFound: 'Posto passível de melhorias ergonômicas relacionadas à permanência em pé, atendimento contínuo e alcances frequentes.',
        generalConditions: 'Ambiente interno, piso regular, circulação moderada de clientes, área de atendimento com balcão refrigerado e vitrine de produtos.',
        accessConditions: 'Acesso ao posto por corredor interno, sem desníveis relevantes, com necessidade de manter área livre para circulação dos trabalhadores.',
        workstationOrganization: 'Balcão com área de apoio para embalagens, caixa próximo e necessidade de reorganização de itens de maior uso dentro da zona de alcance confortável.',
        environmentalConditions: 'Ambiente climatizado parcialmente, iluminação artificial predominante, ruído moderado em horários de pico e ventilação adequada.',
        biomechanicalFactors: 'Permanência em pé por longos períodos, flexão leve de tronco para acesso à vitrine, movimentos repetidos de membros superiores e alcances acima da linha dos ombros em prateleiras superiores.',
        cognitiveFactors: 'Atenção constante ao cliente, memorização de pedidos, conferência de produtos e valores, alternância entre atendimento presencial e solicitações internas.',
        organizationalFactors: 'Ritmo variável conforme fluxo de clientes, maior demanda em horários de pico, pausas dependentes da cobertura da equipe.',
        prescribedTask: 'Atender clientes, pesar produtos, embalar alimentos, repor itens de balcão, orientar sobre produtos e manter o posto organizado.',
        realTask: 'O trabalhador alterna atendimento, reposição rápida, deslocamentos curtos e apoio ao caixa, com permanência predominante em pé durante quase todo o turno.',
        conclusion: 'A função apresenta fatores ergonômicos preliminares relacionados à postura em pé, alcances, repetitividade e organização do trabalho. Recomenda-se adequação da disposição dos materiais, assento para pausas, organização das pausas e reavaliação após implantação das melhorias.',
        requiresAET: false,
        requiresAETJustification: 'Não há indicação imediata de AET, desde que as medidas preliminares sejam implementadas e monitoradas.',
        aep: {
          ...createEmptyAEPFunctionAssessment(),
          identification: {
            unitBranch: unit.name,
            sectorArea: sectAtt.name,
            contemplatedFunctions: roleAtt.name,
            evaluatedActivity: 'Atendimento ao cliente, pesagem e embalagem de produtos, reposição de vitrine e apoio ao caixa.',
            code: 'GHE-01',
          },
          workCharacterization: {
            processDescription: 'Atender clientes, pesar produtos, embalar alimentos, repor itens de balcão, orientar sobre produtos e manter o posto organizado.',
            workCycleDescription: 'O trabalhador alterna atendimento, reposição rápida, deslocamentos curtos e apoio ao caixa, com permanência predominante em pé durante quase todo o turno.',
            workOrganization: {
              workday: '8 horas diárias / 44 horas semanais',
              scale: 'Segunda a sábado, turno diurno',
              overtime: 'Eventualmente em datas comemorativas',
              lunchBreak: '1 hora',
              otherBreaks: 'Pausas informais dependentes do fluxo de clientes',
              taskRotation: 'Não há rodízio formalizado',
              safetyDialogues: 'Semanal',
            },
            toolsAndMaterials: {
              description: 'Balança digital, embalagens plásticas, papel kraft, faca de corte, bandeja expositora, caixa registradora.',
              epis: 'Avental, luvas descartáveis, touca.',
              others: '',
            },
          },
          biomechanics: {
            ...createEmptyAEPFunctionAssessment().biomechanics,
            postureAndReach: [
              { factor: 'Ombro elevado ou abdução sustentada (60°)', assessment: 'Atenção', description: 'Alcance a prateleiras superiores eventualmente.' },
              { factor: 'Punho em desvio/torção frequente ou prolongado', assessment: 'OK', description: '' },
              { factor: 'Preensão forte / pinça prolongada', assessment: 'OK', description: '' },
              { factor: 'Flexão/rotação de tronco repetida ou sustentada', assessment: 'Atenção', description: 'Flexão leve para acesso à vitrine refrigerada.' },
              { factor: 'Pescoço fletido/rodado por tempo prolongado', assessment: 'OK', description: '' },
              { factor: 'Trabalho acima da linha dos ombros', assessment: 'Atenção', description: 'Reposição em prateleiras altas.' },
              { factor: 'Trabalho com braços estendidos / alcance longo', assessment: 'Atenção', description: 'Alcance ao fundo da vitrine.' },
              { factor: 'Postura estática prolongada (sentado ou em pé)', assessment: 'Crítico', description: 'Permanência em pé por quase todo o turno sem assento disponível.' },
            ],
            repetitivenessAndRhythm: [
              { factor: 'Repetição alta de movimentos (mesmo gesto)', assessment: 'Atenção', description: 'Movimentos repetidos de membros superiores no atendimento.' },
              { factor: 'Ritmo imposto por máquina/esteira/sistema', assessment: 'N.A.', description: '' },
              { factor: 'Pressão por tempo / metas agressivas', assessment: 'Atenção', description: 'Pressão em horários de pico.' },
              { factor: 'Pouca margem para variações no método de trabalho', assessment: 'Atenção', description: 'Sequência de atendimento pouco flexível.' },
            ],
            forceAndPhysicalDemand: [
              { factor: 'Força manual elevada (aperto, torção, empurrar/puxar)', assessment: 'OK', description: '' },
              { factor: 'Empurrar/puxar carrinhos (peso/rolagem/piso)', assessment: 'OK', description: '' },
              { factor: 'Sustentação de cargas/braços por tempo prolongado', assessment: 'OK', description: '' },
              { factor: 'Ferramenta inadequada (peso, vibração, pega)', assessment: 'OK', description: '' },
            ],
            manualMaterialHandling: [
              { factor: 'Levantamento/abaixamento frequente de cargas', assessment: 'OK', description: '' },
              { factor: 'Transporte manual de cargas por longas distâncias', assessment: 'OK', description: '' },
              { factor: 'Ajuda mecânica disponível e utilizada?', assessment: 'N.A.', description: '' },
            ],
            furnitureAndWorkstation: [
              { factor: 'Altura de bancada/mesa adequada à tarefa e biotipo', assessment: 'Atenção', description: 'Altura fixa do balcão pode ser inadequada para trabalhadores de menor estatura.' },
              { factor: 'Espaço para pernas/joelhos (quando sentado)', assessment: 'N.A.', description: 'Atividade predominantemente em pé.' },
              { factor: 'Possibilidade de alternância postural (sentado/em pé)', assessment: 'Crítico', description: 'Não há banco ou apoio disponível para pausas sentado.' },
              { factor: 'Assento adequado (ajustes, estofamento, encosto)', assessment: 'Crítico', description: 'Inexistente no posto.' },
              { factor: 'Apoio para pés (quando necessário)', assessment: 'N.A.', description: '' },
              { factor: 'Monitor/teclado/mouse posicionados adequadamente (admin)', assessment: 'N.A.', description: '' },
              { factor: 'Layout favorece fluxo sem posturas forçadas', assessment: 'Atenção', description: 'Reorganização de itens frequentes pode reduzir alcances forçados.' },
            ],
            environmentalComfort: {
              lightingComplaint: 'Não',
              lightingValue: '450 lux',
              lightingDescription: 'Iluminação artificial adequada.',
              noiseComplaint: 'Sim',
              noiseValue: '68 dB',
              noiseDescription: 'Ruído moderado em horários de pico.',
              temperatureComplaint: 'Não',
              temperatureValue: '22°C',
              temperatureDescription: 'Climatizado.',
            },
          },
          scientificTools: [],
          psychosocialAnswers: createEmptyAEPFunctionAssessment().psychosocialAnswers.map((q, i) => ({
            ...q,
            score: [2, 2, 2, 4, 3, 5, 2, 4, 4, 5, 3, 1, 1][i] as number,
          })),
          psychosocialAverages: { demandRhythm: 2.0, autonomyControl: 2.5, roleClarityConflict: 2.17, socialSupportLeadership: 2.33, recognitionJusticePsychSafety: 2.0, overall: 2.2 },
          psychosocialClassification: 'AMARELO',
          psychosocialInterpretation: 'Risco psicossocial moderado. Recomenda-se atenção aos fatores identificados e ações preventivas.',
          aetTriggers: createEmptyAEPFunctionAssessment().aetTriggers.map((t, i) => ({
            ...t,
            answer: i === 0 ? 'Não' : i === 3 ? 'Sim' : 'Não' as 'Sim' | 'Não',
          })),
          finalGuidance: 'Recomenda-se adequação da disposição dos materiais, disponibilização de assento para pausas e organização formal das pausas.',
          decisionJustification: 'Não há indicação imediata de AET, desde que as medidas preliminares sejam implementadas e monitoradas.',
          raciActionPlan: [
            { id: 'raci-aep1-1', riskFactor: 'Postura estática prolongada em pé', action: 'Disponibilizar banco para pausas sentado no posto de atendimento', responsible: 'Gerência da loja', accountable: 'Direção operacional', consulted: 'Ergonomista', informed: 'Colaboradores', deadline: '2026-03-15', priority: 'Alta', status: 'Pendente' },
          ],
          technicalResponsible: {
            name: 'Mariana Costa Albuquerque',
            registration: 'CREFITO-1 123456-F',
            formation: 'Fisioterapeuta do Trabalho e Ergonomista',
            company: 'ErgoPlus Consultoria em Saúde Ocupacional',
            signatureDataUrl: '',
          },
        },
        risks: [
          {
            id: 'risk-aep1-1',
            agent: 'Biomecânico',
            riskFactor: 'Permanência em pé prolongada',
            possibleHealthEffect: 'Fadiga muscular, desconforto lombar e dor em membros inferiores',
            foundSituation: 'Atividade realizada predominantemente em pé, com pausas dependentes do fluxo de clientes.',
            existingControl: 'Pausas informais e alternância eventual com atividades de reposição.',
            improvementProposal: 'Disponibilizar assento adequado para pausas, organizar pausas programadas e alternar tarefas quando possível.',
            probability: 3,
            severity: 3,
            score: 9,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – mobiliário dos postos de trabalho e organização do trabalho',
            evidenceImageDataUrl: '',
            responsible: 'Gerência da loja',
            deadline: '2026-03-15',
            status: 'pendente',
          },
          {
            id: 'risk-aep1-2',
            agent: 'Organizacional',
            riskFactor: 'Ritmo intenso em horários de pico',
            possibleHealthEffect: 'Fadiga, estresse ocupacional e aumento da chance de erros',
            foundSituation: 'Atendimento simultâneo de clientes, reposição e apoio ao caixa em horários de maior movimento.',
            existingControl: 'Reforço eventual de equipe em horários críticos.',
            improvementProposal: 'Definir escala de apoio nos horários de pico e padronizar pausas curtas durante o turno.',
            probability: 3,
            severity: 2,
            score: 6,
            riskLevel: 'MODERADO',
            normativeReference: 'NR-17 – organização do trabalho',
            evidenceImageDataUrl: '',
            responsible: 'Coordenação de atendimento',
            deadline: '2026-03-30',
            status: 'pendente',
          },
        ],
      },
      // ── Função 2: Auxiliar de Produção ─────────────────────────────────────
      {
        ...EMPTY_FUNCTION,
        id:           'aep-f2',
        name:         roleProd.name,
        unit:         unit.name,
        sector:       sectProd.name,
        analysisDate: '2026-01-15',
        numEmployees: '3',
        ghe: 'GHE-02 Produção de Panificação',
        demandFound: 'Posto passível de investigação ergonômica por movimentação manual de cargas, posturas inclinadas e repetitividade no preparo de massas.',
        generalConditions: 'Área interna de produção com bancadas, forno, masseira, cilindro, armários e circulação restrita em alguns pontos.',
        accessConditions: 'Acesso por corredor interno com movimentação de bandejas, caixas de insumos e carrinhos.',
        workstationOrganization: 'Bancadas em altura fixa, utensílios distribuídos em prateleiras e necessidade de melhor posicionamento de insumos de maior peso.',
        environmentalConditions: 'Temperatura elevada próxima aos fornos, iluminação artificial e ruído intermitente de equipamentos.',
        biomechanicalFactors: 'Levantamento de sacos de farinha, empurrar/puxar carrinhos, flexão de tronco, movimentos repetidos de membros superiores e permanência em pé.',
        cognitiveFactors: 'Controle de receitas, tempos de preparo, atenção ao forno, sequência operacional e conferência de qualidade.',
        organizationalFactors: 'Ritmo influenciado pela produção diária, pedidos sob demanda e horários de maior venda.',
        prescribedTask: 'Preparar massas, separar insumos, operar equipamentos de panificação, modelar produtos, organizar bandejas e apoiar a limpeza do setor.',
        realTask: 'O trabalhador realiza preparação de massas, transporte manual de insumos, abastecimento de equipamentos e retirada de bandejas, com esforço físico variável ao longo do turno.',
        conclusion: 'A função apresenta fatores ergonômicos relevantes relacionados à movimentação manual de cargas, calor, posturas e repetitividade. Recomenda-se aprofundamento por AET caso persistam queixas ou caso as medidas de controle não sejam suficientes.',
        requiresAET: true,
        requiresAETJustification: 'Indicação de AET por presença combinada de movimentação manual de cargas, calor, repetitividade e posturas inclinadas.',
        aep: {
          ...createEmptyAEPFunctionAssessment(),
          identification: {
            unitBranch: unit.name,
            sectorArea: sectProd.name,
            contemplatedFunctions: roleProd.name,
            evaluatedActivity: 'Preparação de massas, movimentação de insumos, operação de equipamentos de panificação, retirada de bandejas do forno.',
            code: 'GHE-02',
          },
          workCharacterization: {
            processDescription: 'Preparar massas, separar insumos, operar equipamentos de panificação (masseira, cilindro, forno), modelar produtos, organizar bandejas e apoiar a limpeza do setor.',
            workCycleDescription: 'O trabalhador realiza preparação de massas, transporte manual de insumos, abastecimento de equipamentos e retirada de bandejas, com esforço físico variável ao longo do turno.',
            workOrganization: {
              workday: '8 horas diárias / 44 horas semanais',
              scale: 'Segunda a sábado, madrugada/matutino',
              overtime: 'Eventualmente',
              lunchBreak: '1 hora',
              otherBreaks: 'Pausa de 15 min no meio do turno',
              taskRotation: 'Parcial — alternância entre masseira e forno',
              safetyDialogues: 'Semanal',
            },
            toolsAndMaterials: {
              description: 'Masseira industrial, cilindro de massa, forno combinado, bandejas de alumínio, carrinhos de transporte, balanças.',
              epis: 'Avental térmico, luvas de proteção térmica, calçado antiderrapante, touca, protetor auricular.',
              others: 'Termômetro de forno, cronômetro.',
            },
          },
          biomechanics: {
            ...createEmptyAEPFunctionAssessment().biomechanics,
            postureAndReach: [
              { factor: 'Ombro elevado ou abdução sustentada (60°)', assessment: 'Atenção', description: 'Abastecimento de masseira e retirada de bandejas em posições elevadas.' },
              { factor: 'Punho em desvio/torção frequente ou prolongado', assessment: 'Atenção', description: 'Modelagem manual de produtos.' },
              { factor: 'Preensão forte / pinça prolongada', assessment: 'Atenção', description: 'Manipulação de massa e bandejas pesadas.' },
              { factor: 'Flexão/rotação de tronco repetida ou sustentada', assessment: 'Crítico', description: 'Flexão frequente para abastecimento de masseira e retirada de bandejas em níveis baixos.' },
              { factor: 'Pescoço fletido/rodado por tempo prolongado', assessment: 'Atenção', description: 'Inspeção visual de produtos sobre bancada baixa.' },
              { factor: 'Trabalho acima da linha dos ombros', assessment: 'Atenção', description: 'Colocação de bandejas em carrinhos de altura variável.' },
              { factor: 'Trabalho com braços estendidos / alcance longo', assessment: 'Atenção', description: 'Retirada de bandejas do forno com extensão dos braços.' },
              { factor: 'Postura estática prolongada (sentado ou em pé)', assessment: 'Crítico', description: 'Permanência em pé durante quase toda a jornada.' },
            ],
            repetitivenessAndRhythm: [
              { factor: 'Repetição alta de movimentos (mesmo gesto)', assessment: 'Crítico', description: 'Modelagem repetitiva de produtos de panificação.' },
              { factor: 'Ritmo imposto por máquina/esteira/sistema', assessment: 'Atenção', description: 'Ritmo parcialmente influenciado pelo tempo de fermentação e forno.' },
              { factor: 'Pressão por tempo / metas agressivas', assessment: 'Atenção', description: 'Demanda de produção diária e horários de maior venda.' },
              { factor: 'Pouca margem para variações no método de trabalho', assessment: 'Atenção', description: 'Processo produtivo relativamente padronizado.' },
            ],
            forceAndPhysicalDemand: [
              { factor: 'Força manual elevada (aperto, torção, empurrar/puxar)', assessment: 'Crítico', description: 'Manuseio de sacos de farinha (25 kg), massas pesadas e bandejas.' },
              { factor: 'Empurrar/puxar carrinhos (peso/rolagem/piso)', assessment: 'Atenção', description: 'Transporte de carrinhos com bandejas, piso com irregularidades pontuais.' },
              { factor: 'Sustentação de cargas/braços por tempo prolongado', assessment: 'Atenção', description: 'Sustentação de bandejas durante transferência para o forno.' },
              { factor: 'Ferramenta inadequada (peso, vibração, pega)', assessment: 'N.A.', description: '' },
            ],
            manualMaterialHandling: [
              { factor: 'Levantamento/abaixamento frequente de cargas', assessment: 'Crítico', description: 'Levantamento de sacos de farinha (25 kg) do chão até a masseira.' },
              { factor: 'Transporte manual de cargas por longas distâncias', assessment: 'Atenção', description: 'Transporte de insumos do estoque à área de produção.' },
              { factor: 'Ajuda mecânica disponível e utilizada?', assessment: 'Atenção', description: 'Carrinho disponível, mas nem sempre utilizado para cargas menores.' },
            ],
            furnitureAndWorkstation: [
              { factor: 'Altura de bancada/mesa adequada à tarefa e biotipo', assessment: 'Atenção', description: 'Bancada em altura fixa, pode ser inadequada para modelagem prolongada.' },
              { factor: 'Espaço para pernas/joelhos (quando sentado)', assessment: 'N.A.', description: '' },
              { factor: 'Possibilidade de alternância postural (sentado/em pé)', assessment: 'Crítico', description: 'Não há possibilidade real de alternar postura durante a produção.' },
              { factor: 'Assento adequado (ajustes, estofamento, encosto)', assessment: 'Crítico', description: 'Inexistente no posto.' },
              { factor: 'Apoio para pés (quando necessário)', assessment: 'N.A.', description: '' },
              { factor: 'Monitor/teclado/mouse posicionados adequadamente (admin)', assessment: 'N.A.', description: '' },
              { factor: 'Layout favorece fluxo sem posturas forçadas', assessment: 'Atenção', description: 'Disposição de insumos pesados longe do ponto de uso.' },
            ],
            environmentalComfort: {
              lightingComplaint: 'Não',
              lightingValue: '520 lux',
              lightingDescription: 'Iluminação artificial adequada.',
              noiseComplaint: 'Sim',
              noiseValue: '76 dB',
              noiseDescription: 'Ruído de equipamentos (masseira, forno) em operação simultânea.',
              temperatureComplaint: 'Sim',
              temperatureValue: '32°C',
              temperatureDescription: 'Temperatura elevada próxima aos fornos durante o ciclo de produção.',
            },
          },
          scientificTools: [],
          psychosocialAnswers: createEmptyAEPFunctionAssessment().psychosocialAnswers.map((q, i) => ({
            ...q,
            score: [3, 3, 2, 3, 2, 4, 2, 4, 3, 5, 3, 1, 1][i] as number,
          })),
          psychosocialAverages: { demandRhythm: 2.67, autonomyControl: 2.5, roleClarityConflict: 2.0, socialSupportLeadership: 2.67, recognitionJusticePsychSafety: 1.67, overall: 2.3 },
          psychosocialClassification: 'AMARELO',
          psychosocialInterpretation: 'Risco psicossocial moderado. Recomenda-se atenção aos fatores identificados e ações preventivas.',
          aetTriggers: createEmptyAEPFunctionAssessment().aetTriggers.map((t, i) => ({
            ...t,
            answer: (i === 0 || i === 1 || i === 2 || i === 3) ? 'Sim' : 'Não' as 'Sim' | 'Não',
          })),
          finalGuidance: 'Recomenda-se aprofundamento por AET caso persistam queixas ou caso as medidas de controle não sejam suficientes para eliminar os riscos identificados.',
          decisionJustification: 'Indicação de AET por presença combinada de movimentação manual de cargas, calor, repetitividade e posturas inclinadas.',
          raciActionPlan: [
            { id: 'raci-aep2-1', riskFactor: 'MMC — levantamento de sacos de farinha', action: 'Padronizar uso de carrinho e limitar peso por recipiente a 15 kg', responsible: 'Gerência de produção', accountable: 'Direção', consulted: 'Ergonomista', informed: 'Colaboradores', deadline: '2026-03-20', priority: 'Alta', status: 'Pendente' },
            { id: 'raci-aep2-2', riskFactor: 'Temperatura elevada próxima ao forno', action: 'Avaliar instalação de exaustão localizada e organizar rodízio de tarefas quentes', responsible: 'Manutenção predial', accountable: 'Gerência de produção', consulted: 'SESMT', informed: 'Colaboradores', deadline: '2026-04-15', priority: 'Alta', status: 'Pendente' },
          ],
          technicalResponsible: {
            name: 'Mariana Costa Albuquerque',
            registration: 'CREFITO-1 123456-F',
            formation: 'Fisioterapeuta do Trabalho e Ergonomista',
            company: 'ErgoPlus Consultoria em Saúde Ocupacional',
            signatureDataUrl: '',
          },
        },
        risks: [
          {
            id: 'risk-aep2-1',
            agent: 'Biomecânico',
            riskFactor: 'Movimentação manual de sacos de farinha e insumos',
            possibleHealthEffect: 'Sobrecarga lombar, fadiga muscular e lesões osteomusculares',
            foundSituation: 'Manuseio de insumos com pesos variados, com necessidade de elevação e transporte em curtas distâncias.',
            existingControl: 'Uso eventual de carrinho auxiliar.',
            improvementProposal: 'Padronizar uso de carrinhos, limitar pesos por recipiente, treinar técnica de movimentação e reorganizar estoque próximo ao ponto de uso.',
            probability: 4,
            severity: 3,
            score: 12,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – levantamento, transporte e descarga individual de cargas',
            evidenceImageDataUrl: '',
            responsible: 'Gerência de produção',
            deadline: '2026-03-20',
            status: 'pendente',
          },
          {
            id: 'risk-aep2-2',
            agent: 'Ambiental',
            riskFactor: 'Exposição ao calor próximo aos fornos',
            possibleHealthEffect: 'Desconforto térmico, fadiga e redução da atenção',
            foundSituation: 'Permanência frequente próxima ao forno durante preparo e retirada de produtos.',
            existingControl: 'Ventilação geral do ambiente.',
            improvementProposal: 'Avaliar ventilação/exaustão, organizar rodízio em tarefas próximas ao forno e garantir hidratação acessível.',
            probability: 3,
            severity: 3,
            score: 9,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – condições ambientais de trabalho; avaliação complementar conforme normas aplicáveis',
            evidenceImageDataUrl: '',
            responsible: 'Manutenção predial',
            deadline: '2026-04-15',
            status: 'pendente',
          },
        ],
      },
    ],
  };
};

export const buildMockAETProjectFromCatalog = (): AETProject => {
  const company = getMockCompanyById('company-metalurgica-serra-clara');
  const unit    = getMockUnitById('unit-serra-clara-contagem');
  const sect    = getMockSectorById('sector-serra-usinagem');
  const role    = getMockJobRoleById('role-serra-operador-cnc');

  return {
    id: 'mock-aet-1',
    reportType: 'AET',
    companyName:  company.razaoSocial,
    fantasyName:  company.nomeFantasia,
    cnpj:         company.cnpj,
    address:      buildAddressFromCompany(company),
    unit:         unit.name,
    product:      company.product,
    riskDegree:   company.riskDegree,
    location:     buildLocationFromCompany(company),
    consultoriaLogoDataUrl:    '',
    companyLogoDataUrl:        '',
    responsibleLogoDataUrl:    '',
    evaluatorSignatureDataUrl: '',
    evaluatorName:       'Ricardo Menezes Duarte',
    evaluatorFormation:  'Engenheiro de Segurança do Trabalho e Ergonomista',
    evaluatorCrefito:    'CREA-MG 123456/D',
    evaluatorCompany:    'ErgoSeg Consultoria Técnica',
    date: '2026-01-20',
    introErgonomia:   DEFAULT_AET_INTRO_ERGONOMIA,
    introObjetivo:    DEFAULT_AET_INTRO_OBJETIVO,
    introMetodologia: DEFAULT_AET_INTRO_METODOLOGIA,
    functions: [
      // ── Função: Operador de Máquina CNC ───────────────────────────────────
      {
        ...EMPTY_FUNCTION,
        id:           'aet-f1',
        name:         role.name,
        unit:         unit.name,
        sector:       sect.name,
        analysisDate: '2026-01-20',
        numEmployees: '6',
        demandOrigin: 'Solicitação do setor de Saúde e Segurança do Trabalho após relatos de desconforto lombar e fadiga em membros inferiores entre operadores de máquinas CNC.',
        objective: 'Avaliar de forma aprofundada as condições ergonômicas da atividade de operação de centro de usinagem CNC, identificando fatores de risco e propondo medidas de adequação.',
        demandFound: 'Posto passível de modificações ergonômicas por permanência em pé, manuseio de peças, exigência atencional, repetitividade e posturas inclinadas durante setup e inspeção.',
        marketSituation: company.marketSituation,
        product: company.product,
        productionLocation: unit.productionLocation,
        productionDimension: 'Operação de centros de usinagem, preparação de peças, acionamento de comandos, inspeção dimensional e movimentação de componentes.',
        productionGoals: 'Cumprir ordens de produção diárias, mantendo qualidade dimensional e prazos de entrega.',
        qualityAnalysis: 'A qualidade é verificada por inspeção dimensional com paquímetro, micrômetro e instrumentos específicos, além de conferência por amostragem.',
        qualityEvaluator: 'Inspetor de qualidade e líder de produção.',
        shifts: 'Turno Diurno, Turno Vespertino',
        shiftStart: '07:00',
        shiftEnd: '16:48',
        workDays: 'Seg, Ter, Qua, Qui, Sex',
        overtime: 'Eventualmente',
        pauses: 'Pausa de refeição de 1 hora e pausas curtas conforme necessidade operacional, sem padronização formal para alternância postural.',
        taskRotation: 'Parcialmente',
        bathroomDistance: 'Aproximadamente 60 metros',
        bathroomCondition: 'Adequada',
        hierarchyOrganogram: 'Operador responde ao líder de usinagem, que responde à coordenação de produção.',
        workspaceDescription: 'Área fabril com máquinas CNC dispostas em linha, circulação de carrinhos, bancadas de apoio, armários de ferramentas e pontos de inspeção próximos às máquinas.',
        collabFormation: 'Ensino médio completo e treinamento interno em operação CNC.',
        collabTurn: 'Turno Diurno',
        opinionGender: 'Masculino',
        opinionAge: '31 a 45 anos',
        opinionTime: '5 anos',
        opinionObjective: 'Produzir peças usinadas conforme desenho técnico e programação definida.',
        opinionThermal: 'Regular',
        opinionVentilation: 'Parcialmente adequada',
        opinionVentilationDesc: 'Ventilação geral suficiente na maior parte do turno, com sensação de calor em dias de maior temperatura.',
        opinionLightingSens: 'Adequada',
        opinionLightingDesc: 'Iluminação geral adequada, com necessidade de iluminação localizada em inspeções mais detalhadas.',
        opinionAcoustics: 'Ruído moderado a elevado em operação simultânea de máquinas.',
        opinionEPI: 'Protetor auricular, óculos de segurança, calçado de segurança e luvas para manuseio de peças.',
        opinionEquip: 'Equipamentos adequados, porém algumas bancadas têm altura fixa e exigem inclinação de tronco.',
        opinionCycle: 'Ciclos variáveis conforme peça e programa.',
        opinionLayout: 'Layout funcional, com alguns deslocamentos para busca de ferramentas e instrumentos.',
        opinionDifficulties: 'Desconforto lombar ao realizar setup, inspeção e retirada de peças em posições baixas.',
        opinionPressure: 'Pressão moderada por metas de produção e tempo de máquina parada.',
        opinionRelationship: 'Relacionamento adequado entre colegas.',
        opinionLeadership: 'Liderança acessível para ajustes operacionais.',
        opinionMaintenanceInfluence: 'Manutenções interferem no ciclo quando há parada inesperada.',
        opinionMaintenanceDelay: 'Atrasos eventuais em função da disponibilidade da manutenção.',
        opinionIntercurrences: 'Paradas pontuais por quebra de ferramenta, ajuste dimensional e abastecimento de matéria-prima.',
        effortDynamic: 'Movimentação de peças, abertura e fechamento de portas de máquina, limpeza de cavacos e deslocamentos curtos.',
        effortStatic: 'Permanência em pé durante acompanhamento de ciclos, inspeção e setup.',
        timeAnalysis: 'Ciclos variam entre 8 e 25 minutos por peça, com intervenções do operador para abastecimento, retirada, inspeção e ajustes.',
        loadCarrying: 'Manuseio manual de peças entre 3 kg e 12 kg, com uso de carrinho para lotes maiores.',
        displacement: 'Deslocamentos estimados entre máquina, bancada, instrumentos e área de peças, com média aproximada de 2 a 4 km por turno.',
        maintenanceDesc: 'Manutenções corretivas e preventivas realizadas por equipe interna.',
        maintenanceCausesDelay: 'Sim, quando há parada não programada de máquina.',
        logisticsInfluence: 'Sim',
        logisticsDelay: 'Atrasos no abastecimento podem gerar espera ou acúmulo de peças próximas ao posto.',
        reworkDesc: 'Retrabalho ocorre quando há desvio dimensional identificado na inspeção.',
        reworkWeek: 'Eventual, cerca de 1 a 2 ocorrências por semana.',
        reworkNotApplicable: false,
        usesEquipment: true,
        usesEPI: true,
        equipmentList: [
          {
            id: 'aet-eq1',
            name: 'Centro de Usinagem CNC',
            quantity: '3',
            dimensions: 'Área operacional aproximada 2,5 m x 2,0 m',
            principle: 'eletrico',
            condition: 'Operacional',
            observations: 'Requer abertura frontal para abastecimento e retirada de peças.',
          },
          {
            id: 'aet-eq2',
            name: 'Bancada de inspeção dimensional',
            quantity: '2',
            dimensions: 'Altura fixa aproximada de 90 cm',
            principle: 'manual',
            condition: 'Regular',
            observations: 'Altura não ajustável e apoio limitado para instrumentos.',
          },
        ],
        epiList: [
          {
            id: 'aet-epi1',
            name: 'Protetor auricular',
            mandatory: true,
            occasional: false,
            location: 'Área fabril',
            observations: 'Uso obrigatório durante permanência no setor.',
          },
          {
            id: 'aet-epi2',
            name: 'Óculos de segurança',
            mandatory: true,
            occasional: false,
            location: 'Operação e inspeção',
            observations: 'Uso obrigatório durante operação, inspeção e limpeza.',
          },
        ],
        equipProblems: 'Bancadas auxiliares com altura fixa e suporte de ferramentas sem padronização.',
        cyclePrescribed: 'Conferir ordem de produção, verificar desenho técnico, preparar máquina, posicionar peça, iniciar ciclo, acompanhar operação, retirar peça, realizar inspeção dimensional e encaminhar lote.',
        cycleReal: 'O operador realiza o ciclo prescrito, porém frequentemente alterna com limpeza de cavacos, busca de instrumentos, ajustes de ferramenta e movimentação manual de peças em alturas variadas.',
        postureSittingPct: 5,
        postureStandingPct: 55,
        postureWalkingPct: 25,
        postureCrouchingPct: 10,
        postureOtherPct: 5,
        postureOtherDescription: 'Inclinação de tronco durante setup e inspeção',
        meioAmbiente: 'Ambiente fabril com ruído operacional, iluminação artificial, ventilação geral, piso regular e circulação de carrinhos.',
        diagnosis: 'A atividade apresenta fatores de risco ergonômico relacionados à permanência em pé, movimentação manual de peças, posturas inclinadas, exigência atencional e organização do trabalho. Recomenda-se adequação de bancadas, melhoria na disposição de ferramentas, alternância postural e formalização de pausas.',
        riskLevel: 'ALTO RISCO',
        rulaScore: 'RULA 5 – investigação e mudanças necessárias',
        // NHO 11: pontos [520, 485, 510, 475, 495] ref=500 → média=497 → adequada
        // averageLux=497, tolerance=450, seventyPct=347.9, ratio=1.09
        illumination: {
          ...EMPTY_ILLUMINATION,
          location: 'Setor de Usinagem – Máquina CNC 02',
          date: '2026-01-20',
          lightingType: 'Artificial geral com apoio localizado eventual',
          objective: 'Avaliar os níveis de iluminância no posto de operação e inspeção dimensional.',
          justification: 'Verificar adequação da iluminação para leitura de instrumentos, inspeção dimensional e operação segura.',
          environmentDescription: 'Área fabril interna com luminárias distribuídas no teto e bancada de inspeção próxima à máquina.',
          lightingSystem: 'Luminárias LED industriais em distribuição geral.',
          activities: 'Operação CNC, inspeção visual e dimensional, leitura de desenho técnico e instrumentos de medição.',
          criteria: 'Avaliação simplificada por média dos pontos medidos, conforme módulo inicial NHO 11 do sistema.',
          modelType: 'SIMPLE_AVERAGE',
          referenceLux: 500,
          measurementPoints: [
            { id: 'nho-p1', label: 'P1', lux: 520 },
            { id: 'nho-p2', label: 'P2', lux: 485 },
            { id: 'nho-p3', label: 'P3', lux: 510 },
            { id: 'nho-p4', label: 'P4', lux: 475 },
            { id: 'nho-p5', label: 'P5', lux: 495 },
          ],
          resultLux: '497',
          conclusion: 'adequada',
          conclusionText: 'A iluminância média de 497 lux está acima do limiar mínimo de 90% (450 lux) da referência de 500 lux. Iluminação adequada.',
          interpretation: 'A iluminância média medida (497 lux) é igual ou superior ao limite mínimo de 450 lux (90 % do valor de referência de 500 lux). A iluminação do ambiente está adequada segundo os critérios da NHO 11 – Fundacentro.',
        },
        scientificMethods: [
          {
            id: 'aet-sm1',
            methodName: 'RULA',
            description: 'Avaliação postural durante setup e retirada de peças, considerando membros superiores, tronco, pescoço e membros inferiores.',
            result: 'Pontuação final 5',
            riskClassification: 'Moderado',
            interpretation: 'O resultado indica necessidade de investigação e implantação de mudanças no posto e na organização da atividade.',
            imageDataUrl: '',
            recommendations: 'Ajustar altura de bancadas, reduzir alcances, aproximar instrumentos e revisar sequência de setup.',
          },
        ],
        risks: [
          {
            id: 'risk-aet1-1',
            agent: 'Biomecânico',
            riskFactor: 'Postura em pé prolongada com inclinação de tronco',
            possibleHealthEffect: 'Dor lombar, fadiga muscular e desconforto em membros inferiores',
            foundSituation: 'Operador permanece em pé durante a maior parte do turno e realiza inclinações de tronco durante setup, inspeção e retirada de peças.',
            existingControl: 'Pausas informais e alternância parcial entre operação e inspeção.',
            improvementProposal: 'Adequar altura das bancadas, disponibilizar apoio para alternância postural, revisar posicionamento de peças e formalizar pausas.',
            probability: 4,
            severity: 3,
            score: 12,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – organização do trabalho, mobiliário e condições dos postos de trabalho',
            evidenceImageDataUrl: '',
            responsible: 'Engenharia de Processos',
            deadline: '2026-04-20',
            status: 'pendente',
          },
          {
            id: 'risk-aet1-2',
            agent: 'Biomecânico',
            riskFactor: 'Manuseio manual de peças metálicas',
            possibleHealthEffect: 'Sobrecarga de membros superiores, ombros e coluna lombar',
            foundSituation: 'Peças entre 3 kg e 12 kg são movimentadas manualmente entre máquina, bancada e carrinhos.',
            existingControl: 'Carrinhos disponíveis para lotes maiores.',
            improvementProposal: 'Definir limite de peso por manuseio individual, utilizar dispositivos auxiliares para peças mais pesadas e aproximar carrinhos da zona de trabalho.',
            probability: 3,
            severity: 4,
            score: 12,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – levantamento, transporte e descarga individual de cargas',
            evidenceImageDataUrl: '',
            responsible: 'Coordenação de Produção',
            deadline: '2026-04-30',
            status: 'pendente',
          },
          {
            id: 'risk-aet1-3',
            agent: 'Cognitivo',
            riskFactor: 'Exigência de atenção contínua e conferência dimensional',
            possibleHealthEffect: 'Fadiga mental, erros de inspeção e aumento da tensão ocupacional',
            foundSituation: 'Operador acompanha ciclos, interpreta desenho técnico, verifica medidas e responde a intercorrências da máquina.',
            existingControl: 'Treinamento operacional e apoio do líder.',
            improvementProposal: 'Padronizar checklist de setup, organizar instrumentos por frequência de uso e prever pausas curtas em ciclos longos.',
            probability: 3,
            severity: 3,
            score: 9,
            riskLevel: 'ALTO RISCO',
            normativeReference: 'NR-17 – organização do trabalho e exigências cognitivas',
            evidenceImageDataUrl: '',
            responsible: 'Qualidade e Produção',
            deadline: '2026-05-10',
            status: 'pendente',
          },
        ],
      },
    ],
  };
};

// ── Public factory functions ─────────────────────────────────────────────────

export const createMockAEPProject = (): AETProject =>
  buildMockAEPProjectFromCatalog();

export const createMockAETProject = (): AETProject =>
  buildMockAETProjectFromCatalog();
