import {
  AETProject,
  EMPTY_FUNCTION,
  EMPTY_ILLUMINATION,
  DEFAULT_AEP_INTRO_ERGONOMIA,
  DEFAULT_AEP_INTRO_OBJETIVO,
  DEFAULT_AEP_INTRO_METODOLOGIA,
  DEFAULT_AET_INTRO_ERGONOMIA,
  DEFAULT_AET_INTRO_OBJETIVO,
  DEFAULT_AET_INTRO_METODOLOGIA,
} from '../types';

// ── Projeto AEP — Padaria Horizonte Azul Ltda. ──────────────────────────────

export const createMockAEPProject = (): AETProject => ({
  id: 'mock-aep-1',
  reportType: 'AEP',
  companyName: 'Padaria Horizonte Azul Ltda.',
  fantasyName: 'Padaria Horizonte Azul',
  cnpj: '12.345.678/0001-90',
  address: 'Rua das Palmeiras, 250 – Boa Vista – Recife/PE',
  unit: 'Loja Matriz',
  product: 'Panificação, confeitaria e atendimento ao público',
  riskDegree: '2',
  location: 'Recife – PE',
  consultoriaLogoDataUrl: '',
  companyLogoDataUrl: '',
  responsibleLogoDataUrl: '',
  evaluatorSignatureDataUrl: '',
  evaluatorName: 'Mariana Costa Albuquerque',
  evaluatorFormation: 'Fisioterapeuta do Trabalho e Ergonomista',
  evaluatorCrefito: 'CREFITO-1 123456-F',
  evaluatorCompany: 'ErgoPlus Consultoria em Saúde Ocupacional',
  date: '2026-01-15',
  introErgonomia: DEFAULT_AEP_INTRO_ERGONOMIA,
  introObjetivo: DEFAULT_AEP_INTRO_OBJETIVO,
  introMetodologia: DEFAULT_AEP_INTRO_METODOLOGIA,
  functions: [
    // ── Função 1: Atendente de Balcão ────────────────────────────────────────
    {
      ...EMPTY_FUNCTION,
      id: 'aep-f1',
      name: 'Atendente de Balcão',
      unit: 'Loja Matriz',
      sector: 'Atendimento',
      analysisDate: '2026-01-15',
      numEmployees: '4',
      ghe: 'GHE-01 Atendimento e Balcão',
      demandFound: 'Posto passível de melhorias ergonômicas relacionadas à permanência em pé, atendimento contínuo e alcances frequentes.',
      generalConditions: 'Ambiente interno, piso regular, circulação moderada de clientes, área de atendimento com balcão refrigerado e vitrine de produtos.',
      accessConditions: 'Acesso ao posto por corredor interno, sem desníveis relevantes, com necessidade de manter área livre para circulação dos trabalhadores.',
      workstationOrganization: 'Balcão com área de apoio para embalagens, caixa próximo e necessidade de reorganização de itens de maior uso dentro da zona de alcance confortável.',
      environmentalConditions: 'Ambiente climatizado parcialmente, iluminação artificial predominante, ruído moderado em horários de pico e ventilação adequada.',
      biomechanicalFactors: 'Permanência em pé por longos períodos, flexão leve de tronco para acesso à vitrine, movimentos repetidos de membros superiores e alcances acima da linha dos ombros em prateleiras superiores.',
      cognitiveFactors: 'Atenção constante ao cliente, memorização de pedidos, conferência de produtos e valores, alternância entre atendimento presencial e solicitações internas.',
      organizationalFactors: 'Ritmo variável conforme fluxo de clientes, maior demanda em horários de pico, pausas dependentes da cobertura da equipe.',
      prescribedTask: 'Atender clientes, pesar produtos, embalar alimentos, repor itens de balcão, orientar sobre produtos e manter o posto organizado.',
      realTask: 'O trabalhador alterna atendimento, reposição rápida, deslocamentos curtos e apoio ao caixa, com permanência predominante em pé durante quase todo o turno.',
      conclusion: 'A função apresenta fatores ergonômicos preliminares relacionados à postura em pé, alcances, repetitividade e organização do trabalho. Recomenda-se adequação da disposição dos materiais, assento para pausas, organização das pausas e reavaliação após implantação das melhorias.',
      requiresAET: false,
      requiresAETJustification: 'Não há indicação imediata de AET, desde que as medidas preliminares sejam implementadas e monitoradas.',
      risks: [
        {
          id: 'risk-aep1-1',
          agent: 'Biomecânico',
          riskFactor: 'Permanência em pé prolongada',
          possibleHealthEffect: 'Fadiga muscular, desconforto lombar e dor em membros inferiores',
          foundSituation: 'Atividade realizada predominantemente em pé, com pausas dependentes do fluxo de clientes.',
          existingControl: 'Pausas informais e alternância eventual com atividades de reposição.',
          improvementProposal: 'Disponibilizar assento adequado para pausas, organizar pausas programadas e alternar tarefas quando possível.',
          probability: 3,
          severity: 3,
          score: 9,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – mobiliário dos postos de trabalho e organização do trabalho',
          evidenceImageDataUrl: '',
          responsible: 'Gerência da loja',
          deadline: '2026-03-15',
          status: 'pendente',
        },
        {
          id: 'risk-aep1-2',
          agent: 'Organizacional',
          riskFactor: 'Ritmo intenso em horários de pico',
          possibleHealthEffect: 'Fadiga, estresse ocupacional e aumento da chance de erros',
          foundSituation: 'Atendimento simultâneo de clientes, reposição e apoio ao caixa em horários de maior movimento.',
          existingControl: 'Reforço eventual de equipe em horários críticos.',
          improvementProposal: 'Definir escala de apoio nos horários de pico e padronizar pausas curtas durante o turno.',
          probability: 3,
          severity: 2,
          score: 6,
          riskLevel: 'MODERADO',
          normativeReference: 'NR-17 – organização do trabalho',
          evidenceImageDataUrl: '',
          responsible: 'Coordenação de atendimento',
          deadline: '2026-03-30',
          status: 'pendente',
        },
      ],
    },
    // ── Função 2: Auxiliar de Produção de Panificação ────────────────────────
    {
      ...EMPTY_FUNCTION,
      id: 'aep-f2',
      name: 'Auxiliar de Produção de Panificação',
      unit: 'Loja Matriz',
      sector: 'Produção',
      analysisDate: '2026-01-15',
      numEmployees: '3',
      ghe: 'GHE-02 Produção de Panificação',
      demandFound: 'Posto passível de investigação ergonômica por movimentação manual de cargas, posturas inclinadas e repetitividade no preparo de massas.',
      generalConditions: 'Área interna de produção com bancadas, forno, masseira, cilindro, armários e circulação restrita em alguns pontos.',
      accessConditions: 'Acesso por corredor interno com movimentação de bandejas, caixas de insumos e carrinhos.',
      workstationOrganization: 'Bancadas em altura fixa, utensílios distribuídos em prateleiras e necessidade de melhor posicionamento de insumos de maior peso.',
      environmentalConditions: 'Temperatura elevada próxima aos fornos, iluminação artificial e ruído intermitente de equipamentos.',
      biomechanicalFactors: 'Levantamento de sacos de farinha, empurrar/puxar carrinhos, flexão de tronco, movimentos repetidos de membros superiores e permanência em pé.',
      cognitiveFactors: 'Controle de receitas, tempos de preparo, atenção ao forno, sequência operacional e conferência de qualidade.',
      organizationalFactors: 'Ritmo influenciado pela produção diária, pedidos sob demanda e horários de maior venda.',
      prescribedTask: 'Preparar massas, separar insumos, operar equipamentos de panificação, modelar produtos, organizar bandejas e apoiar a limpeza do setor.',
      realTask: 'O trabalhador realiza preparação de massas, transporte manual de insumos, abastecimento de equipamentos e retirada de bandejas, com esforço físico variável ao longo do turno.',
      conclusion: 'A função apresenta fatores ergonômicos relevantes relacionados à movimentação manual de cargas, calor, posturas e repetitividade. Recomenda-se aprofundamento por AET caso persistam queixas ou caso as medidas de controle não sejam suficientes.',
      requiresAET: true,
      requiresAETJustification: 'Indicação de AET por presença combinada de movimentação manual de cargas, calor, repetitividade e posturas inclinadas.',
      risks: [
        {
          id: 'risk-aep2-1',
          agent: 'Biomecânico',
          riskFactor: 'Movimentação manual de sacos de farinha e insumos',
          possibleHealthEffect: 'Sobrecarga lombar, fadiga muscular e lesões osteomusculares',
          foundSituation: 'Manuseio de insumos com pesos variados, com necessidade de elevação e transporte em curtas distâncias.',
          existingControl: 'Uso eventual de carrinho auxiliar.',
          improvementProposal: 'Padronizar uso de carrinhos, limitar pesos por recipiente, treinar técnica de movimentação e reorganizar estoque próximo ao ponto de uso.',
          probability: 4,
          severity: 3,
          score: 12,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – levantamento, transporte e descarga individual de cargas',
          evidenceImageDataUrl: '',
          responsible: 'Gerência de produção',
          deadline: '2026-03-20',
          status: 'pendente',
        },
        {
          id: 'risk-aep2-2',
          agent: 'Ambiental',
          riskFactor: 'Exposição ao calor próximo aos fornos',
          possibleHealthEffect: 'Desconforto térmico, fadiga e redução da atenção',
          foundSituation: 'Permanência frequente próxima ao forno durante preparo e retirada de produtos.',
          existingControl: 'Ventilação geral do ambiente.',
          improvementProposal: 'Avaliar ventilação/exaustão, organizar rodízio em tarefas próximas ao forno e garantir hidratação acessível.',
          probability: 3,
          severity: 3,
          score: 9,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – condições ambientais de trabalho; avaliação complementar conforme normas aplicáveis',
          evidenceImageDataUrl: '',
          responsible: 'Manutenção predial',
          deadline: '2026-04-15',
          status: 'pendente',
        },
      ],
    },
  ],
});

// ── Projeto AET — Metalúrgica Serra Clara S.A. ──────────────────────────────

export const createMockAETProject = (): AETProject => ({
  id: 'mock-aet-1',
  reportType: 'AET',
  companyName: 'Metalúrgica Serra Clara S.A.',
  fantasyName: 'Serra Clara Componentes Industriais',
  cnpj: '98.765.432/0001-10',
  address: 'Avenida Industrial, 1450 – Cinco – Contagem/MG',
  unit: 'Planta Industrial Contagem',
  product: 'Fabricação de componentes metálicos para máquinas industriais',
  riskDegree: '3',
  location: 'Contagem – MG',
  consultoriaLogoDataUrl: '',
  companyLogoDataUrl: '',
  responsibleLogoDataUrl: '',
  evaluatorSignatureDataUrl: '',
  evaluatorName: 'Ricardo Menezes Duarte',
  evaluatorFormation: 'Engenheiro de Segurança do Trabalho e Ergonomista',
  evaluatorCrefito: 'CREA-MG 123456/D',
  evaluatorCompany: 'ErgoSeg Consultoria Técnica',
  date: '2026-01-20',
  introErgonomia: DEFAULT_AET_INTRO_ERGONOMIA,
  introObjetivo: DEFAULT_AET_INTRO_OBJETIVO,
  introMetodologia: DEFAULT_AET_INTRO_METODOLOGIA,
  functions: [
    // ── Função: Operador de Usinagem CNC ─────────────────────────────────────
    {
      ...EMPTY_FUNCTION,
      id: 'aet-f1',
      name: 'Operador de Usinagem CNC',
      unit: 'Planta Industrial Contagem',
      sector: 'Usinagem',
      analysisDate: '2026-01-20',
      numEmployees: '6',
      demandOrigin: 'Solicitação do setor de Saúde e Segurança do Trabalho após relatos de desconforto lombar e fadiga em membros inferiores entre operadores de máquinas CNC.',
      objective: 'Avaliar de forma aprofundada as condições ergonômicas da atividade de operação de centro de usinagem CNC, identificando fatores de risco e propondo medidas de adequação.',
      demandFound: 'Posto passível de modificações ergonômicas por permanência em pé, manuseio de peças, exigência atencional, repetitividade e posturas inclinadas durante setup e inspeção.',
      marketSituation: 'Empresa com produção contínua para clientes do setor industrial, com demanda variável conforme carteira de pedidos.',
      product: 'Componentes metálicos usinados sob especificação técnica.',
      productionLocation: 'Setor de usinagem CNC, área fabril interna.',
      productionDimension: 'Operação de centros de usinagem, preparação de peças, acionamento de comandos, inspeção dimensional e movimentação de componentes.',
      productionGoals: 'Cumprir ordens de produção diárias, mantendo qualidade dimensional e prazos de entrega.',
      qualityAnalysis: 'A qualidade é verificada por inspeção dimensional com paquímetro, micrômetro e instrumentos específicos, além de conferência por amostragem.',
      qualityEvaluator: 'Inspetor de qualidade e líder de produção.',
      shifts: 'Turno Diurno, Turno Vespertino',
      shiftStart: '07:00',
      shiftEnd: '16:48',
      workDays: 'Seg, Ter, Qua, Qui, Sex',
      overtime: 'Eventualmente',
      pauses: 'Pausa de refeição de 1 hora e pausas curtas conforme necessidade operacional, sem padronização formal para alternância postural.',
      taskRotation: 'Parcialmente',
      bathroomDistance: 'Aproximadamente 60 metros',
      bathroomCondition: 'Adequada',
      hierarchyOrganogram: 'Operador responde ao líder de usinagem, que responde à coordenação de produção.',
      workspaceDescription: 'Área fabril com máquinas CNC dispostas em linha, circulação de carrinhos, bancadas de apoio, armários de ferramentas e pontos de inspeção próximos às máquinas.',
      collabFormation: 'Ensino médio completo e treinamento interno em operação CNC.',
      collabTurn: 'Turno Diurno',
      opinionGender: 'Masculino',
      opinionAge: '31 a 45 anos',
      opinionTime: '5 anos',
      opinionObjective: 'Produzir peças usinadas conforme desenho técnico e programação definida.',
      opinionThermal: 'Regular',
      opinionVentilation: 'Parcialmente adequada',
      opinionVentilationDesc: 'Ventilação geral suficiente na maior parte do turno, com sensação de calor em dias de maior temperatura.',
      opinionLightingSens: 'Adequada',
      opinionLightingDesc: 'Iluminação geral adequada, com necessidade de iluminação localizada em inspeções mais detalhadas.',
      opinionAcoustics: 'Ruído moderado a elevado em operação simultânea de máquinas.',
      opinionEPI: 'Protetor auricular, óculos de segurança, calçado de segurança e luvas para manuseio de peças.',
      opinionEquip: 'Equipamentos adequados, porém algumas bancadas têm altura fixa e exigem inclinação de tronco.',
      opinionCycle: 'Ciclos variáveis conforme peça e programa.',
      opinionLayout: 'Layout funcional, com alguns deslocamentos para busca de ferramentas e instrumentos.',
      opinionDifficulties: 'Desconforto lombar ao realizar setup, inspeção e retirada de peças em posições baixas.',
      opinionPressure: 'Pressão moderada por metas de produção e tempo de máquina parada.',
      opinionRelationship: 'Relacionamento adequado entre colegas.',
      opinionLeadership: 'Liderança acessível para ajustes operacionais.',
      opinionMaintenanceInfluence: 'Manutenções interferem no ciclo quando há parada inesperada.',
      opinionMaintenanceDelay: 'Atrasos eventuais em função da disponibilidade da manutenção.',
      opinionIntercurrences: 'Paradas pontuais por quebra de ferramenta, ajuste dimensional e abastecimento de matéria-prima.',
      effortDynamic: 'Movimentação de peças, abertura e fechamento de portas de máquina, limpeza de cavacos e deslocamentos curtos.',
      effortStatic: 'Permanência em pé durante acompanhamento de ciclos, inspeção e setup.',
      timeAnalysis: 'Ciclos variam entre 8 e 25 minutos por peça, com intervenções do operador para abastecimento, retirada, inspeção e ajustes.',
      loadCarrying: 'Manuseio manual de peças entre 3 kg e 12 kg, com uso de carrinho para lotes maiores.',
      displacement: 'Deslocamentos estimados entre máquina, bancada, instrumentos e área de peças, com média aproximada de 2 a 4 km por turno.',
      maintenanceDesc: 'Manutenções corretivas e preventivas realizadas por equipe interna.',
      maintenanceCausesDelay: 'Sim, quando há parada não programada de máquina.',
      logisticsInfluence: 'Sim',
      logisticsDelay: 'Atrasos no abastecimento podem gerar espera ou acúmulo de peças próximas ao posto.',
      reworkDesc: 'Retrabalho ocorre quando há desvio dimensional identificado na inspeção.',
      reworkWeek: 'Eventual, cerca de 1 a 2 ocorrências por semana.',
      reworkNotApplicable: false,
      usesEquipment: true,
      usesEPI: true,
      equipmentList: [
        {
          id: 'aet-eq1',
          name: 'Centro de Usinagem CNC',
          quantity: '3',
          dimensions: 'Área operacional aproximada 2,5 m x 2,0 m',
          principle: 'eletrico',
          condition: 'Operacional',
          observations: 'Requer abertura frontal para abastecimento e retirada de peças.',
        },
        {
          id: 'aet-eq2',
          name: 'Bancada de inspeção dimensional',
          quantity: '2',
          dimensions: 'Altura fixa aproximada de 90 cm',
          principle: 'manual',
          condition: 'Regular',
          observations: 'Altura não ajustável e apoio limitado para instrumentos.',
        },
      ],
      epiList: [
        {
          id: 'aet-epi1',
          name: 'Protetor auricular',
          mandatory: true,
          occasional: false,
          location: 'Área fabril',
          observations: 'Uso obrigatório durante permanência no setor.',
        },
        {
          id: 'aet-epi2',
          name: 'Óculos de segurança',
          mandatory: true,
          occasional: false,
          location: 'Operação e inspeção',
          observations: 'Uso obrigatório durante operação, inspeção e limpeza.',
        },
      ],
      equipProblems: 'Bancadas auxiliares com altura fixa e suporte de ferramentas sem padronização.',
      cyclePrescribed: 'Conferir ordem de produção, verificar desenho técnico, preparar máquina, posicionar peça, iniciar ciclo, acompanhar operação, retirar peça, realizar inspeção dimensional e encaminhar lote.',
      cycleReal: 'O operador realiza o ciclo prescrito, porém frequentemente alterna com limpeza de cavacos, busca de instrumentos, ajustes de ferramenta e movimentação manual de peças em alturas variadas.',
      postureSittingPct: 5,
      postureStandingPct: 55,
      postureWalkingPct: 25,
      postureCrouchingPct: 10,
      postureOtherPct: 5,
      postureOtherDescription: 'Inclinação de tronco durante setup e inspeção',
      meioAmbiente: 'Ambiente fabril com ruído operacional, iluminação artificial, ventilação geral, piso regular e circulação de carrinhos.',
      diagnosis: 'A atividade apresenta fatores de risco ergonômico relacionados à permanência em pé, movimentação manual de peças, posturas inclinadas, exigência atencional e organização do trabalho. Recomenda-se adequação de bancadas, melhoria na disposição de ferramentas, alternância postural e formalização de pausas.',
      riskLevel: 'ALTO RISCO',
      rulaScore: 'RULA 5 – investigação e mudanças necessárias',
      // NHO 11: pontos [520, 485, 510, 475, 495] ref=500 → média=497 → adequada
      // averageLux=497, tolerance=450, seventyPct=347.9, ratio=1.09
      illumination: {
        ...EMPTY_ILLUMINATION,
        location: 'Setor de Usinagem – Máquina CNC 02',
        date: '2026-01-20',
        lightingType: 'Artificial geral com apoio localizado eventual',
        objective: 'Avaliar os níveis de iluminância no posto de operação e inspeção dimensional.',
        justification: 'Verificar adequação da iluminação para leitura de instrumentos, inspeção dimensional e operação segura.',
        environmentDescription: 'Área fabril interna com luminárias distribuídas no teto e bancada de inspeção próxima à máquina.',
        lightingSystem: 'Luminárias LED industriais em distribuição geral.',
        activities: 'Operação CNC, inspeção visual e dimensional, leitura de desenho técnico e instrumentos de medição.',
        criteria: 'Avaliação simplificada por média dos pontos medidos, conforme módulo inicial NHO 11 do sistema.',
        modelType: 'SIMPLE_AVERAGE',
        referenceLux: 500,
        measurementPoints: [
          { id: 'nho-p1', label: 'P1', lux: 520 },
          { id: 'nho-p2', label: 'P2', lux: 485 },
          { id: 'nho-p3', label: 'P3', lux: 510 },
          { id: 'nho-p4', label: 'P4', lux: 475 },
          { id: 'nho-p5', label: 'P5', lux: 495 },
        ],
        resultLux: '497',
        conclusion: 'adequada',
        conclusionText: 'A iluminância média de 497 lux está acima do limiar mínimo de 90% (450 lux) da referência de 500 lux. Iluminação adequada.',
        interpretation: 'A iluminância média medida (497 lux) é igual ou superior ao limite mínimo de 450 lux (90 % do valor de referência de 500 lux). A iluminação do ambiente está adequada segundo os critérios da NHO 11 – Fundacentro.',
      },
      scientificMethods: [
        {
          id: 'aet-sm1',
          methodName: 'RULA',
          description: 'Avaliação postural durante setup e retirada de peças, considerando membros superiores, tronco, pescoço e membros inferiores.',
          result: 'Pontuação final 5',
          riskClassification: 'Moderado',
          interpretation: 'O resultado indica necessidade de investigação e implantação de mudanças no posto e na organização da atividade.',
          imageDataUrl: '',
          recommendations: 'Ajustar altura de bancadas, reduzir alcances, aproximar instrumentos e revisar sequência de setup.',
        },
      ],
      risks: [
        {
          id: 'risk-aet1-1',
          agent: 'Biomecânico',
          riskFactor: 'Postura em pé prolongada com inclinação de tronco',
          possibleHealthEffect: 'Dor lombar, fadiga muscular e desconforto em membros inferiores',
          foundSituation: 'Operador permanece em pé durante a maior parte do turno e realiza inclinações de tronco durante setup, inspeção e retirada de peças.',
          existingControl: 'Pausas informais e alternância parcial entre operação e inspeção.',
          improvementProposal: 'Adequar altura das bancadas, disponibilizar apoio para alternância postural, revisar posicionamento de peças e formalizar pausas.',
          probability: 4,
          severity: 3,
          score: 12,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – organização do trabalho, mobiliário e condições dos postos de trabalho',
          evidenceImageDataUrl: '',
          responsible: 'Engenharia de Processos',
          deadline: '2026-04-20',
          status: 'pendente',
        },
        {
          id: 'risk-aet1-2',
          agent: 'Biomecânico',
          riskFactor: 'Manuseio manual de peças metálicas',
          possibleHealthEffect: 'Sobrecarga de membros superiores, ombros e coluna lombar',
          foundSituation: 'Peças entre 3 kg e 12 kg são movimentadas manualmente entre máquina, bancada e carrinhos.',
          existingControl: 'Carrinhos disponíveis para lotes maiores.',
          improvementProposal: 'Definir limite de peso por manuseio individual, utilizar dispositivos auxiliares para peças mais pesadas e aproximar carrinhos da zona de trabalho.',
          probability: 3,
          severity: 4,
          score: 12,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – levantamento, transporte e descarga individual de cargas',
          evidenceImageDataUrl: '',
          responsible: 'Coordenação de Produção',
          deadline: '2026-04-30',
          status: 'pendente',
        },
        {
          id: 'risk-aet1-3',
          agent: 'Cognitivo',
          riskFactor: 'Exigência de atenção contínua e conferência dimensional',
          possibleHealthEffect: 'Fadiga mental, erros de inspeção e aumento da tensão ocupacional',
          foundSituation: 'Operador acompanha ciclos, interpreta desenho técnico, verifica medidas e responde a intercorrências da máquina.',
          existingControl: 'Treinamento operacional e apoio do líder.',
          improvementProposal: 'Padronizar checklist de setup, organizar instrumentos por frequência de uso e prever pausas curtas em ciclos longos.',
          probability: 3,
          severity: 3,
          score: 9,
          riskLevel: 'ALTO RISCO',
          normativeReference: 'NR-17 – organização do trabalho e exigências cognitivas',
          evidenceImageDataUrl: '',
          responsible: 'Qualidade e Produção',
          deadline: '2026-05-10',
          status: 'pendente',
        },
      ],
    },
  ],
});
