import type { Permission, UserRole } from './authTypes';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: [
    'USERS_VIEW',
    'USERS_CREATE',
    'USERS_EDIT',
    'USERS_DELETE',
    'PROJECTS_VIEW',
    'PROJECTS_CREATE',
    'PROJECTS_EDIT',
    'PROJECTS_DELETE',
    'AEP_VIEW',
    'AEP_CREATE',
    'AEP_EDIT',
    'AEP_DELETE',
    'AEP_PRINT',
    'AET_VIEW',
    'AET_CREATE',
    'AET_EDIT',
    'AET_DELETE',
    'AET_PRINT',
    'CATALOG_VIEW',
    'CATALOG_EDIT',
    'SETTINGS_VIEW',
    'SETTINGS_EDIT',
  ],

  TECHNICAL_RESPONSIBLE: [
    'PROJECTS_VIEW',
    'PROJECTS_CREATE',
    'PROJECTS_EDIT',
    'AEP_VIEW',
    'AEP_CREATE',
    'AEP_EDIT',
    'AEP_PRINT',
    'AET_VIEW',
    'AET_CREATE',
    'AET_EDIT',
    'AET_PRINT',
    'CATALOG_VIEW',
    'CATALOG_EDIT',
  ],

  CONSULTANT: [
    'PROJECTS_VIEW',
    'PROJECTS_CREATE',
    'PROJECTS_EDIT',
    'AEP_VIEW',
    'AEP_CREATE',
    'AEP_EDIT',
    'AEP_PRINT',
    'AET_VIEW',
    'AET_CREATE',
    'AET_EDIT',
    'AET_PRINT',
    'CATALOG_VIEW',
  ],

  CLIENT_VIEWER: [
    'PROJECTS_VIEW',
    'AEP_VIEW',
    'AEP_PRINT',
    'AET_VIEW',
    'AET_PRINT',
  ],
};
